### ISSUE TITLE
Create Database

### ISSUE THREAD

**Issue by findnewfriends** [findnewfriends/e-commerce-chaton#1]
I would create the databse like the diagram

**Comment by remiboivin-zz** [comment]
> diagram

You should join the database schema. we can refer to it in the future :)

**Comment by findnewfriends** [comment]
![Capture d’écran 2020-06-01 à 12 25 28](https://user-images.githubusercontent.com/66007045/83444028-0c0e7d00-a44b-11ea-95fb-8098e5fb3c49.png)
